### ISSUE TITLE
2.0.1版本无法导入QQ音乐歌单

### ISSUE THREAD

**Issue by Voring** [canxin121/app_rhyme#101]
之前是可以导入QQ音乐歌单的，更新了2.0.1无法导入
![2E53F871-79D8-4A72-9571-0F57D1DB5E8A](https://github.com/user-attachments/assets/814b3196-4839-427c-85fa-2d8ba5fc6721)

**Comment by canxin121** [comment]
这是不可能的，从来没有适配过qq音乐，都无法解析qq音乐的链接

**Comment by canxin121** [comment]
而且注意目前2.0.1是在测试阶段，甚至有在修改数据库定义，建议更新时先导出数据库为json作为备份
