### ISSUE TITLE
mac 端  -- 歌单顺序播放及切换播放问题

### ISSUE THREAD

**Issue by liuxeuman** [canxin121/app_rhyme#19]
mac 端歌单列表，一首歌播放完毕后，不会切换下一首歌曲，并且手动也无法切换，只能关闭后，重新打开选择别的歌曲进行播放

软件版本：v1.0.5
mac系统配置： m1  14.0 系统

**Comment by canxin121** [comment]
检查一下网络问题，更换网络环境试试，关闭代理软件试试，我询问其他用户无法复现这个问题

**Comment by canxin121** [comment]
可以发送一个录屏，我看一下具体表现

**Comment by liuxeuman** [comment]
> 可以发送一个录屏，我看一下具体表现

不好意思，可能是我的网络问题，刚才是开着代理使用，
