### ISSUE TITLE
状态栏概率显示异常？

### ISSUE THREAD

**Issue by Virgo-0910** [canxin121/app_rhyme#25]
安卓和iOS都有概率性状态栏不沉浸或者说不反色 
~~安卓左右侧返回不是返回上一界面~~
安卓三星s22u oneui6.1  iOS 15pm 17.6

**Comment by Virgo-0910** [comment]
灵动岛直接点击或展开点击无法回到app内

**Comment by canxin121** [comment]
这些ui细节全都还没实现，目前正在重构后端代码以适配多音乐平台➕统一外部类型为Triat Object，基本已经完成。后面完成ffi bind之后，预计过两天就可以ui部分开工。

**Comment by Virgo-0910** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
