### ISSUE TITLE
[无法复现]IOS 旧版歌单丢失，无法拖动进度条

### ISSUE THREAD

**Issue by fdgdssds** [canxin121/app_rhyme#26]
需要覆盖安装的注意一点，因为是重构的版本，之前收藏的数据会被清空。
在播放的时候切换音质好像没反应？![image](https://github.com/canxin121/app_rhyme/assets/139738981/6f970010-a1e5-44a8-a189-ea49062cf2fe)

**Comment by canxin121** [comment]
关闭重新打开试试，我做了数据库更新，但是刚才确实遇到了第一次打开没显示成功，我关闭重新打开又显示出来了

**Comment by canxin121** [comment]
歌单数据正常了吗，音质切换确实有bug，下一版和黑夜模式一起修复下

**Comment by fdgdssds** [comment]
> 歌单数据正常了吗，音质切换确实有bug，下一版和黑夜模式一起修复下

1、播放歌曲的时候进度条不能拖动
2、直接点击歌曲播放完后，会重复播放，而不是默认播放下一曲。

**Comment by canxin121** [comment]
> > 歌单数据正常了吗，音质切换确实有bug，下一版和黑夜模式一起修复下
> 
> 1、播放歌曲的时候进度条不能拖动
> 2、直接点击歌曲播放完后，会重复播放，而不是默认播放下一曲。

均无法复现，在我的设备上没有这两个问题，测试几次都无法复现

**Comment by canxin121** [comment]
> > 歌单数据正常了吗，音质切换确实有bug，下一版和黑夜模式一起修复下
> 
> 1、播放歌曲的时候进度条不能拖动
> 2、直接点击歌曲播放完后，会重复播放，而不是默认播放下一曲。

话说歌单啥情况了，我这里歌单也没有被清空

**Comment by fdgdssds** [comment]
是iOS版本？

**Comment by canxin121** [comment]
> 是iOS版本？

对，安卓确实缺少固定证书无法覆盖安装

**Comment by fdgdssds** [comment]
https://github.com/canxin121/app_rhyme/assets/139738981/d7c4dc29-3e7c-4e35-acba-6925933f2235

**Comment by canxin121** [comment]
> https://github.com/canxin121/app_rhyme/assets/139738981/d7c4dc29-3e7c-4e35-acba-6925933f2235

![正在上传 346243885...]

**Comment by canxin121** [comment]
> https://github.com/canxin121/app_rhyme/assets/139738981/d7c4dc29-3e7c-4e35-acba-6925933f2235

**Comment by canxin121** [comment]
> > 歌单数据正常了吗，音质切换确实有bug，下一版和黑夜模式一起修复下
> 
> 1、播放歌曲的时候进度条不能拖动
> 2、直接点击歌曲播放完后，会重复播放，而不是默认播放下一曲。

https://github.com/canxin121/app_rhyme/assets/69547456/b7e85868-ad43-4f2f-bbaa-cb98d94e6eed

**Comment by canxin121** [comment]
无法复现的话，很难修，你可以删了重装试试，太玄学了

**Comment by fdgdssds** [comment]
会不会是音源的问题

**Comment by canxin121** [comment]
> 会不会是音源的问题

应该无关，我播放的同样是2000kflac的格式，你可以试试其他音质正不正常

**Comment by fdgdssds** [comment]
目前1.07版本正常了，切换音质，和拉动进度条都正常了。
还有一个问题是：在收藏界面单击音乐播放他会单曲循环，可以改成播放完直接下一曲？还有优化一下单击歌曲自动跳转到播放播放器界面，在播放器界面可以左侧滑动返回上一个界面，iOS很多软件都是这样返回比较习惯，目前是下拉返回。
![image](https://github.com/canxin121/app_rhyme/assets/139738981/fb294623-ac79-408b-bd32-b8ede238832f)

**Comment by canxin121** [comment]
> 目前1.07版本正常了，切换音质，和拉动进度条都正常了。
> 还有一个问题是：在收藏界面单击音乐播放他会单曲循环，可以改成播放完直接下一曲？还有优化一下单击歌曲自动跳转到播放播放器界面，在播放器界面可以左侧滑动返回上一个界面，iOS很多软件都是这样返回比较习惯，目前是下拉返回。
> ![image](https://github.com/canxin121/app_rhyme/assets/139738981/fb294623-ac79-408b-bd32-b8ede238832f)

播放界面模仿AppleMusic，所以是下拉返回。点击歌单内音乐直接添加所有音乐恐怕不太合适，后续可以添加一个设定项来切换，自动跳转同样添加一个设定项吧。 我先close这个issue了，后续问题可以开新的issue或者discussion
