### ISSUE TITLE
Release时APK签名不同导致无法覆盖旧版本

### ISSUE THREAD

**Issue by canxin121** [canxin121/app_rhyme#27]
直接使用的github action进行release构建且无缓存，未配置Apk证书，导致每次release时的签名都不一致，新版本无法覆盖旧版本。

由于本人日常使用iphone+巨魔，刚刚了解到安卓的Apk版本覆盖机制需要签名一致。🤦🏻‍♀️

**Comment by wtflmao** [comment]
是这样的
