### ISSUE TITLE
ios缓存播放失败

### ISSUE THREAD

**Issue by popoXD** [canxin121/app_rhyme#29]
wy音源缓存后无法播放，文件里的格式为 _hires.unknown
自动切换到kw音源缓存后，缓存文件里是正常的文件格式，断网播放会自动切换音源，并播放失败

**Comment by canxin121** [comment]
1. wy音源确实在ios上缓存后无法播放，这个比较玄学，不是很好修
2. 缓存机制依赖音质，这个有问题，需要修一下，比较好修

下个版本尽可能修复

**Comment by canxin121** [comment]
全部修复了，提前想用的话 来github action下载https://github.com/canxin121/app_rhyme/actions/runs/9884276956

**Comment by z9244741** [comment]
！[上传IMG_1557.png...]() 搜索出来的歌曲添加到歌单。搜索界面有概率出现这种情况。

**Comment by popoXD** [comment]
又发现一个问题，无法取消缓存。从文件 目录里删除文件，打开软件依然带有缓存字样且提示缓存失败无法再次缓存

**Comment by canxin121** [comment]
> 又发现一个问题，无法取消缓存。从文件 目录里删除文件，打开软件依然带有缓存字样且提示缓存失败无法再次缓存

用的是最新的Action Build版本吗？我用的是，我这里无法复现这个问题
https://github.com/user-attachments/assets/b574de5a-56d5-431b-806c-7c9ed1bb1355

**Comment by popoXD** [comment]
![IMG_0766](https://github.com/user-attachments/assets/7cfd1a1c-75cb-4b84-8f78-03775c340fcd)
下载的这个ios的

**Comment by canxin121** [comment]
> ![IMG_0766](https://github.com/user-attachments/assets/7cfd1a1c-75cb-4b84-8f78-03775c340fcd)
> 
> 下载的这个ios的

有很多不同时间的Build Action，这个图片是最新的一个Build Action的文件吗？如果是的话可以录制一个bug出现的视频吗？这样我可以更快了解

**Comment by popoXD** [comment]
哦哦哦，下了3天前的

**Comment by popoXD** [comment]
下载昨天的就好了哈哈
