### ISSUE TITLE
ios 搜索界面有时候空白。

### ISSUE THREAD

**Issue by z9244741** [canxin121/app_rhyme#30]
搜索出来的歌曲添加到歌单。搜索界面有概率出现空白页面。！[上传IMG_1557.png...]()

**Comment by canxin121** [comment]
https://github.com/canxin121/app_rhyme/actions/runs/9884276956
使用上面的action中的安装包试一下，里面修复了一个有关搜索歌曲的bug

**Comment by z9244741** [comment]
我就说用的这个链接里面最新的。ios 缓存不能播放的问题已经没有了。 搜索界面有时候空白 还是存在。不知道你可以看到上传的图片不。

**Comment by canxin121** [comment]
> 我就说用的这个链接里面最新的。ios 缓存不能播放的问题已经没有了。 搜索界面有时候空白 还是存在。不知道你可以看到上传的图片不。

显示上传中，看不到

**Comment by canxin121** [comment]
我也遇到了，我继续修下

**Comment by canxin121** [comment]
https://github.com/canxin121/app_rhyme/actions/runs/9886074787 等构建完ipa试试

**Comment by z9244741** [comment]
我试了。没有出现了。好像已经解决了。谢谢。
