### ISSUE TITLE
音源正常但是播放不了

### ISSUE THREAD

**Issue by zyzz-zmh** [canxin121/app_rhyme#37]

**Comment by canxin121** [comment]
请检查 网络状况和代理设置，尝试切换网络，关闭代理

**Comment by zyzz-zmh** [comment]
> 请检查 网络状况和代理设置，尝试切换网络，关闭代理


Uploading RPReplay_Final1721655755_2.mp4…

**Comment by canxin121** [comment]
> > 请检查 网络状况和代理设置，尝试切换网络，关闭代理
> 
> Uploading RPReplay_Final1721655755_2.mp4…

一直显示uploading，看不到视频，重新上传试试

**Comment by zyzz-zmh** [comment]
https://f.ws28.cn/f/enox9dzqhm2 复制链接到浏览器打开 我这梯子不行

> 请检查 网络状况和代理设置，尝试切换网络，关闭代理

**Comment by canxin121** [comment]
你的音源文件错了吧，导入链接试试

**Comment by zyzz-zmh** [comment]
> Owner

换了2个源都一样，不知道是不是我不会用

**Comment by canxin121** [comment]
> > Owner
> 
> 换了2个源都一样，不知道是不是我不会用

查看issue找找别人的源吧，不能和其他软件的音源通用的，只能是evc或dart文件哦

**Comment by zyzz-zmh** [comment]
> > > Owner
> > 
> > 
> > 换了2个源都一样，不知道是不是我不会用
> 
> 查看issue找找别人的源吧，不能和其他软件的音源通用的，只能是evc或dart文件哦

哦哦谢谢解答，还有希望能支持酷狗吧

**Comment by canxin121** [comment]
> > > > Owner
> > > 
> > > 
> > > 换了2个源都一样，不知道是不是我不会用
> > 
> > 
> > 查看issue找找别人的源吧，不能和其他软件的音源通用的，只能是evc或dart文件哦
> 
> 哦哦谢谢解答，还有希望能支持酷狗吧

最近几天有点生病，后面写完桌面版再说，桌面版已经快写完了

**Comment by zyzz-zmh** [comment]
> > > Owner
> > 
> > 
> > 换了2个源都一样，不知道是不是我不会用
> 
> 查看issue找找别人的源吧，不能和其他软件的音源通用的，只能是evc或dart文件哦

可以用了，但发现歌词滚动不是逐字的，这样看得别扭，建议取消滚动

**Comment by canxin121** [comment]
zyzz-zmh ***@***.***>于2024年7月22日 周一22:51写道：

> Owner
>
> 换了2个源都一样，不知道是不是我不会用
>
> 查看issue找找别人的源吧，不能和其他软件的音源通用的，只能是evc或dart文件哦
>
> 可以用了，但发现歌词滚动不是逐字的，这样看得别扭，建议取消滚动
>
歌词使用的是第三方库哦，等后面重写吧

**Comment by zyzz-zmh** [comment]
> zyzz-zmh ***@***.***>于2024年7月22日 周一22:51写道：
> Owner 换了2个源都一样，不知道是不是我不会用 查看issue找找别人的源吧，不能和其他软件的音源通用的，只能是evc或dart文件哦 可以用了，但发现歌词滚动不是逐字的，这样看得别扭，建议取消滚动
> 歌词使用的是第三方库哦，等后面重写吧

哦哦大佬辛苦辛苦
