### ISSUE TITLE
请问最低支持安卓几？可否自适应宽屏？想用在车机上

### ISSUE THREAD

**Issue by heylogo1** [canxin121/app_rhyme#39]

**Comment by canxin121** [comment]
自适应宽屏正在写，最低安卓版本我也不清楚哦，没有试过

**Comment by canxin121** [comment]
> > 自适应宽屏正在写，最低安卓版本我也不清楚哦，没有试过
> 
> 
> 
> 那最低支持安卓api版本多少呢？
build.gradle中指定的minsdkversion为19，但是可能也会受到rust构建的影响
