### ISSUE TITLE
苹果自签启动白屏

### ISSUE THREAD

**Issue by Qanfa** [canxin121/app_rhyme#43]
1.08版前两天自签还能正常打开，今天打开就是白屏，之前自签1.07和1.06都是启动都是白屏一样，1.05版本没问题

**Comment by Qanfa** [comment]
![IMG_3839](https://github.com/user-attachments/assets/d45c2ba5-318f-450e-8f10-3cfef90500a6)

**Comment by canxin121** [comment]
应该是签名的问题吧？这种我不太清楚哦，我是巨魔用户

**Comment by Qanfa** [comment]
应该是签名问题，我的iPad就没事（巨魔）发自我的 iPhone在 2024年7月25日，12:30，canxin ***@***.***> 写道：﻿
应该是签名的问题吧？这种我不太清楚哦，我是巨魔用户
