### ISSUE TITLE
全部缓存会有问题

### ISSUE THREAD

**Issue by popoXD** [canxin121/app_rhyme#9]
ios版歌单里选择全部缓存，删除全部缓存也没啥用，歌曲文件还在离线听不了，但其实已经下载了，单一条可以缓存，也能听

**Comment by canxin121** [comment]
复现了，马上修好0.0

**Comment by canxin121** [comment]
修好了，我发一个新的测试release

**Comment by canxin121** [comment]
安装最新release试试，我这里实机运行已经没问题了
